Calories/Models/Food.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Calories.Models
{
    public class Food
    {
        [Key]
        public long ID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public double Calories { get; set; }

        [Required]
        public Unit Unit { get; set; }

        public virtual Person Owner { get; set; }
        [Required]
        public long OwnerID { get; set; }
    }

    public enum Unit
    {
        Unknown,
        Packet,
        Each,
        [Display(Name = "Per Gram")]
        Gram,
    }
}

Calories/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Calories.Lib;
using Calories.Models;
using Calories.Services;
using Calories.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SQLitePCL;

namespace Calories.Controllers
{
    [Authorize(Roles = Static.RoleFood)]
    public class FoodController : BaseController
    {
        private readonly AuthService _auth;
        private readonly CalorieService _calories;

        public FoodController(AuthService auth, CalorieService calories)
        {
            _auth = auth;
            _calories = calories;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_calories.GetFoods());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind("Name", "Calories", "Unit")] FoodVM model)
        {
            if (await _calories.FoodExistsAsync(model.Name))
            {
                ModelState.AddModelError(nameof(model.Name), $"Food {model.Name} alredy exists");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Person who = await _auth.GetCurrentPersonAsync(User);

            Food created = await _calories.AddFoodAsync(who, model.Name, model.Calories, model.Unit);

            return RedirectWithMessage(nameof(Index), "Food {0} was created", created.Name);
        }

        [HttpGet]
        public async Task<ActionResult> EditAsync(long? id)
        {
            if (id == null)
            {
                return RedirectWithMessage(nameof(Index), "Missing id");
            }
            Food current = await _calories.GetFoodAsync(id.Value);
            if (current == null)
            {
                return RedirectWithMessage(nameof(Index), "Can't find food with id {0}", id.Value);
            }

            return View(new FoodVM
            {
                Calories = current.Calories,
                Name = current.Name,
                Unit = current.Unit,
            });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(long? id, FoodVM model)
        {
            if (id == null)
            {
                return RedirectWithMessage(nameof(Index), "Missing id");
            }
            Food current = await _calories.GetFoodAsync(id.Value);
            if (current == null)
            {
                return RedirectWithMessage(nameof(Index), "Can't find food with id {0}", id.Value);
            }

            if (model.Name != current.Name && await _calories.FoodExistsAsync(model.Name))
            {
                ModelState.AddModelError(nameof(model.Name), $"Food {model.Name} alredy exists");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _calories.EditFoodAsync(current, model.Name, model.Calories, model.Unit);

            return RedirectWithMessage(nameof(Index), "Food {0} has been updated", current.Name);
        }
    }
}

Calories/Views/Food/Create.cshtml
@model FoodVM
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Manage Foods";
}

<form asp-controller="Food" asp-action="Create">

    <dl>
        <dt><label asp-for="Name"></label></dt>
        <dd><input asp-for="Name" /></dd>
        <dt><label asp-for="Calories"></label></dt>
        <dd><input asp-for="Calories" /></dd>

        <dt><label asp-for="Unit"></label></dt>
        <dd><select asp-for="Unit" asp-items="Html.GetEnumSelectList<Unit>()"></select></dd>
    </dl>
    <button type="submit">Create food</button>
</form>

Calories/Views/Food/Edit.cshtml
@model FoodVM
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Edit Food";
}

<form method="post" autocomplete="off">

    <dl>
        <dt><label asp-for="Name"></label></dt>
        <dd>
            <span asp-validation-for="Name"></span>
            <input asp-for="Name" />
        </dd>
        <dt> 
            <span asp-validation-for="Calories"></span>
            <label asp-for="Calories"></label>
        </dt>
        <dd><input asp-for="Calories" /></dd>

        <dt><label asp-for="Unit"></label></dt>
        <dd> 
            <span asp-validation-for="Unit"></span>
            <select asp-for="Unit" asp-items="Html.GetEnumSelectList<Unit>()"></select>
        </dd>
    </dl>
    <button type="submit">Save changes</button>
</form>

Calories/Views/Food/Index.cshtml
@model IEnumerable<Food>
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Manage Foods";
}

<p><a asp-action="Create">Add a new food</a></p>
<p><a asp-action="Index" asp-controller="Home">Back to home</a></p>

<table>
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(x => x.Name)</th>
            <th>@Html.DisplayNameFor(x => x.Calories)</th>
            <th>@Html.DisplayNameFor(x => x.Unit)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Food f in Model)
        {
            <tr>
                <td>@Html.DisplayFor(x => f.Name)</td>
                <td>@Html.DisplayFor(x => f.Calories)</td>
                <td>@Html.DisplayFor(x => f.Unit)</td>
                <td><a asp-action="Edit" asp-route-id="@f.ID">Edit</a></td>
            </tr>
        }
    </tbody>
</table>